server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Supporto per il routing lato client (Single Page Application):
        # Se il file o la directory richiesta non esistono fisicamente sul disco,
        # Nginx restituisce index.html permettendo a React Router di gestire la rotta
        try_files $uri $uri/ /index.html;
    }
}
